#ifndef __MPIR_CONFIG_H__
#define __MPIR_CONFIG_H__
#ifdef MPIR_CUDA_ACC
#define mpf_init MPIR_NAME_PREFIX(mpf_init)
#define mpf_clear MPIR_NAME_PREFIX(mpf_clear)
#define mpf_neg MPIR_NAME_PREFIX(mpf_neg)
#define mpf_set MPIR_NAME_PREFIX(mpf_set)
#define mpf_set_d MPIR_NAME_PREFIX(mpf_set_d)
#define mpf_get_d MPIR_NAME_PREFIX(mpf_get_d)
#define mpf_get_d_2exp MPIR_NAME_PREFIX(mpf_get_d_2exp)
#define mpf_mul_ui MPIR_NAME_PREFIX(mpf_mul_ui)
#define mpf_div_ui MPIR_NAME_PREFIX(mpf_div_ui)
#define mpf_add MPIR_NAME_PREFIX(mpf_add)
#define mpf_sub MPIR_NAME_PREFIX(mpf_sub)
#define mpf_mul MPIR_NAME_PREFIX(mpf_mul)
#define mpf_div MPIR_NAME_PREFIX(mpf_div)
#define mpf_div_ui MPIR_NAME_PREFIX(mpf_div_ui)
#define mpf_cmp_d MPIR_NAME_PREFIX(mpf_cmp_d)
#define mpf_cmp MPIR_NAME_PREFIX(mpf_cmp)


#define mpn_add_n MPIR_NAME_PREFIX(mpn_add_n)
#define mpn_sub_n MPIR_NAME_PREFIX(mpn_sub_n)
#define mpn_add  MPIR_NAME_PREFIX(mpn_add )
#define mpn_add_1 MPIR_NAME_PREFIX(mpn_add_1)
#define mpn_cmp  MPIR_NAME_PREFIX(mpn_cmp )
#define mpn_sub MPIR_NAME_PREFIX(mpn_sub)
#define mpn_sub_1 MPIR_NAME_PREFIX(mpn_sub_1)
//#define mpn_invert_limb  MPIR_NAME_PREFIX(mpn_invert_limb)

#define __gmp_extract_double MPIR_NAME_PREFIX(__gmp_extract_double)
#define mpn_get_d MPIR_NAME_PREFIX(mpn_get_d)
#define mpn_mul_1 MPIR_NAME_PREFIX(mpn_mul_1)
#define mpn_divrem_1 MPIR_NAME_PREFIX(mpn_divrem_1)
#define mpn_mod_1 MPIR_NAME_PREFIX(mpn_mod_1)
#define mpn_mod_1_1 MPIR_NAME_PREFIX(mpn_mod_1_1)
#define mpn_mod_1_2 MPIR_NAME_PREFIX(mpn_mod_1_2)
#define mpn_mod_1_3 MPIR_NAME_PREFIX(mpn_mod_1_3)
#define mpn_mul_n MPIR_NAME_PREFIX(mpn_mul_n)
#define mpn_mul MPIR_NAME_PREFIX(mpn_mul)
#define mpn_sqr MPIR_NAME_PREFIX(mpn_sqr)

#define mpn_mul_basecase MPIR_NAME_PREFIX(mpn_mul_basecase)
#define mpn_toom4_interpolate MPIR_NAME_PREFIX(mpn_toom4_interpolate)
#define mpn_toom53_mul MPIR_NAME_PREFIX(mpn_toom53_mul)
#define mpn_toom8h_mul MPIR_NAME_PREFIX(mpn_toom8h_mul)
#define mpn_toom4_mul MPIR_NAME_PREFIX(mpn_toom4_mul)
#define mpn_toom3_mul MPIR_NAME_PREFIX(mpn_toom3_mul)
#define mpn_toom3_mul_n MPIR_NAME_PREFIX(mpn_toom3_mul_n)
#define mpn_toom4_mul_n MPIR_NAME_PREFIX(mpn_toom4_mul_n)
#define mpn_toom42_mul  MPIR_NAME_PREFIX(mpn_toom42_mul)
#define mpn_toom32_mul  MPIR_NAME_PREFIX(mpn_toom32_mul)
#define mpn_toom3_sqr_n  MPIR_NAME_PREFIX(mpn_toom3_sqr_n)
#define mpn_toom4_sqr_n  MPIR_NAME_PREFIX(mpn_toom4_sqr_n)
#define mpn_toom8_sqr_n   MPIR_NAME_PREFIX(mpn_toom8_sqr_n )
#define mpn_toom3_interpolate  MPIR_NAME_PREFIX(mpn_toom3_interpolate)
#define tc4_addlsh1_unsigned MPIR_NAME_PREFIX(tc4_addlsh1_unsigned)
#define tc4_addmul_1 MPIR_NAME_PREFIX(tc4_addmul_1)
#define tc4_add MPIR_NAME_PREFIX(tc4_add)
#define mpn_toom_couple_handling MPIR_NAME_PREFIX(mpn_toom_couple_handling)
#define mpn_kara_sqr_n MPIR_NAME_PREFIX(mpn_kara_sqr_n)
#define mpn_invert  MPIR_NAME_PREFIX(mpn_invert )
#define mpn_lshift MPIR_NAME_PREFIX(mpn_lshift)
#define mpn_rshift MPIR_NAME_PREFIX(mpn_rshift)
#define mpn_addmul_1 MPIR_NAME_PREFIX(mpn_addmul_1)
#define mpn_addmul_2 MPIR_NAME_PREFIX(mpn_addmul_2)
#define mpn_submul_1 MPIR_NAME_PREFIX(mpn_submul_1)
#define mpn_kara_mul_n MPIR_NAME_PREFIX(mpn_kara_mul_n)
#define mpn_com_n  MPIR_NAME_PREFIX(mpn_com_n)
#define mpn_toom_eval_pm1 MPIR_NAME_PREFIX(mpn_toom_eval_pm1)
#define mpn_toom_eval_pm2 MPIR_NAME_PREFIX(mpn_toom_eval_pm2)
#define mpn_toom_eval_pm2exp MPIR_NAME_PREFIX(mpn_toom_eval_pm2exp)
#define mpn_toom_eval_pm2rexp MPIR_NAME_PREFIX(mpn_toom_eval_pm2rexp)
#define mpn_toom_eval_dgr3_pm1 MPIR_NAME_PREFIX(mpn_toom_eval_dgr3_pm1)
#define mpn_toom_interpolate_16pts MPIR_NAME_PREFIX(mpn_toom_interpolate_16pts)
#define mpn_divexact_1 MPIR_NAME_PREFIX(mpn_divexact_1)
#define mpn_sqr_basecase  MPIR_NAME_PREFIX(mpn_sqr_basecase)
#define mpn_divexact_by3c MPIR_NAME_PREFIX(mpn_divexact_by3c)
#define mpn_divexact_byfobm1 MPIR_NAME_PREFIX(mpn_divexact_byfobm1)

#define mpn_divrem_euclidean_qr_1 MPIR_NAME_PREFIX(mpn_divrem_euclidean_qr_1)
#define mpn_divrem_euclidean_qr_2 MPIR_NAME_PREFIX(mpn_divrem_euclidean_qr_2)
#define mpn_divrem_euclidean_r_1 MPIR_NAME_PREFIX(mpn_divrem_euclidean_r_1)
#define mpn_rsh_divrem_hensel_qr_1 MPIR_NAME_PREFIX(mpn_rsh_divrem_hensel_qr_1)
#define mpn_divrem_1 MPIR_NAME_PREFIX(mpn_divrem_1)
#define mpn_divrem_2 MPIR_NAME_PREFIX(mpn_divrem_2)
#define mpn_sb_div_qr MPIR_NAME_PREFIX(mpn_sb_div_qr)
#define mpn_dc_div_qr_n MPIR_NAME_PREFIX(mpn_dc_div_qr_n)
#define mpn_dc_div_qr MPIR_NAME_PREFIX(mpn_dc_div_qr)
#define mpn_inv_div_qr MPIR_NAME_PREFIX(mpn_inv_div_qr)
#define mpn_inv_div_qr_n MPIR_NAME_PREFIX(mpn_inv_div_qr_n)
#define mpn_invert_trunc MPIR_NAME_PREFIX(mpn_invert_trunc)
#define tc4_add_unsigned MPIR_NAME_PREFIX(tc4_add_unsigned)
#define tc4_sub MPIR_NAME_PREFIX(tc4_sub)
#define tc4_lshift MPIR_NAME_PREFIX(tc4_lshift)
#define mpn_tdiv_qr  MPIR_NAME_PREFIX(mpn_tdiv_qr)
#define __gmp_exception MPIR_NAME_PREFIX(__gmp_exception)
#define __gmp_divide_by_zero MPIR_NAME_PREFIX(__gmp_divide_by_zero)
#define __gmp_sqrt_of_negative MPIR_NAME_PREFIX(__gmp_sqrt_of_negative)
#define __gmp_invalid_operation MPIR_NAME_PREFIX(__gmp_invalid_operation)
#define TMP_ALLOC_FUNC MPIR_NAME_PREFIX(TMP_ALLOC_FUNC)
#endif // MPIR_CUDA_ACC
#endif